# Generated by Django 5.2.14 on 2026-06-01 12:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WatchTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('url', models.URLField(max_length=1000)),
                ('description', models.TextField(blank=True)),
                ('vertical', models.CharField(choices=[('pricing', 'Pricing / competitive'), ('compliance', 'Compliance / legal'), ('regulatory', 'Regulatory / government'), ('status', 'Status / uptime'), ('docs', 'Docs / changelog'), ('generic', 'Generic')], default='generic', max_length=20)),
                ('watch_instructions', models.TextField(blank=True)),
                ('extraction_schema', models.JSONField(blank=True, default=dict)),
                ('fetch_strategy', models.CharField(choices=[('auto', 'Auto (API/feed first, then browser)'), ('api', 'API / feed only'), ('browser', 'Browser render only')], default='auto', max_length=10)),
                ('check_interval_minutes', models.PositiveIntegerField(default=1440)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('blocked', 'Blocked'), ('error', 'Error')], default='active', max_length=10)),
                ('status_note', models.CharField(blank=True, max_length=500)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['status'], name='monitoring__status_a15a25_idx')],
            },
        ),
        migrations.CreateModel(
            name='Snapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fetched_at', models.DateTimeField(db_index=True)),
                ('fetch_method', models.CharField(choices=[('api', 'API / feed'), ('http', 'Plain HTTP'), ('browser', 'Browser render')], default='http', max_length=10)),
                ('http_status', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('ok', models.BooleanField(default=True)),
                ('blocked', models.BooleanField(default=False)),
                ('status_note', models.TextField(blank=True)),
                ('raw_content', models.TextField(blank=True)),
                ('content_text', models.TextField(blank=True)),
                ('content_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('extracted', models.JSONField(blank=True, default=dict)),
                ('screenshot_path', models.CharField(blank=True, max_length=500)),
                ('fetch_duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='monitoring.watchtarget')),
            ],
            options={
                'ordering': ['-fetched_at'],
            },
        ),
        migrations.CreateModel(
            name='Change',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('detected_at', models.DateTimeField(db_index=True)),
                ('detection_method', models.CharField(choices=[('naive', 'Naive (raw diff)'), ('semantic', 'Semantic (field + embedding)')], default='semantic', max_length=10)),
                ('change_type', models.CharField(choices=[('content', 'Content'), ('price', 'Price'), ('availability', 'Availability'), ('clause', 'Clause / policy'), ('status', 'Status'), ('structure', 'Structure'), ('other', 'Other')], default='content', max_length=20)),
                ('is_meaningful', models.BooleanField(default=False)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='info', max_length=10)),
                ('significance_score', models.FloatField(blank=True, null=True)),
                ('summary', models.TextField(blank=True)),
                ('why_it_matters', models.TextField(blank=True)),
                ('field_diffs', models.JSONField(blank=True, default=list)),
                ('text_diff', models.TextField(blank=True)),
                ('dedup_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('current_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes_as_current', to='monitoring.snapshot')),
                ('previous_snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='changes_as_previous', to='monitoring.snapshot')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='monitoring.watchtarget')),
            ],
            options={
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('change', 'Meaningful change'), ('blocked', 'Target blocked'), ('error', 'Fetch/processing error'), ('info', 'Informational')], default='change', max_length=10)),
                ('level', models.CharField(choices=[('info', 'Info'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='info', max_length=10)),
                ('title', models.CharField(max_length=300)),
                ('body', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved')], default='new', max_length=12)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('change', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='monitoring.change')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='monitoring.watchtarget')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='snapshot',
            index=models.Index(fields=['target', '-fetched_at'], name='monitoring__target__b3b345_idx'),
        ),
        migrations.AddIndex(
            model_name='snapshot',
            index=models.Index(fields=['target', 'content_hash'], name='monitoring__target__43719a_idx'),
        ),
        migrations.AddIndex(
            model_name='change',
            index=models.Index(fields=['target', '-detected_at'], name='monitoring__target__69b0ca_idx'),
        ),
        migrations.AddIndex(
            model_name='change',
            index=models.Index(fields=['is_meaningful', 'severity'], name='monitoring__is_mean_19bdd5_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['target', '-created_at'], name='monitoring__target__08b27d_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['status', 'level'], name='monitoring__status_9824d7_idx'),
        ),
    ]
