# Generated by Django 5.2.14 on 2026-06-02 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_snapshot_embedding'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(db_index=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ok', 'OK'), ('skipped', 'Skipped (unchanged)'), ('blocked', 'Blocked'), ('error', 'Error')], default='ok', max_length=10)),
                ('fetch_method', models.CharField(blank=True, max_length=10)),
                ('http_status', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
                ('change', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='monitoring.change')),
                ('snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='monitoring.snapshot')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='monitoring.watchtarget')),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['target', '-started_at'], name='monitoring__target__d598bf_idx')],
            },
        ),
    ]
