# Generated by Django 5.2.14 on 2026-06-02 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LLMUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('operation', models.CharField(max_length=40)),
                ('model', models.CharField(max_length=120)),
                ('prompt_tokens', models.PositiveIntegerField(default=0)),
                ('completion_tokens', models.PositiveIntegerField(default=0)),
                ('total_tokens', models.PositiveIntegerField(default=0)),
                ('cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=12)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='llm_usage', to='monitoring.watchtarget')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['operation', '-created_at'], name='llm_llmusag_operati_2ab97d_idx')],
            },
        ),
    ]
